
name: check secret void

on:
  push:
    branches: teste-disabled

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret
        env:
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "SECRET VAZIO"
            exit 1
          fi

          echo "SECRET EXISTE"    