name: Docker Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

      dockerfile:
        required: false
        type: string
        default: Dockerfile

      registry:
        required: true
        type: string
      REGISTRY_USERNAME:
        required: true  
        type: string      

    secrets:


      REGISTRY_PASSWORD:
        required: true

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build
        run: |
          docker build \
            -f ${{ inputs.dockerfile }} \
            -t ${{ inputs.registry }}/${{ inputs.image_name }}:${{ github.sha }} .

      - name: Push
        run: |
          docker push \
            ${{ inputs.registry }}/${{ inputs.image_name }}:${{ github.sha }}