name: Docker Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

      dockerfile:
        required: false
        type: string
        default: Dockerfile

      registry:
        required: false
        type: string
      REGISTRY_USERNAME:
        required: true  
        type: string      
    secrets:

      REGISTRY_PASSWORD:
        required: true

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  NODE_OPTIONS: "--no-deprecation"

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check secret
        env:
          MY_SECRET: ${{ secrets.REGISTRY_PASSWORD }}
        if: ${{ env.MY_SECRET == '' }}
        run: echo "MY_SECRET não existe"

      - name: Secret not found
        env:
          MY_SECRET: ${{ secrets.REGISTRY_PASSWORD }}
        if: ${{ env.MY_SECRET != '' }}
        run: echo "MY_SECRET não existe"


      - name: Validate variables
        env:
          VAR1: ${{ inputs.image_name }}
          VAR2: ${{ inputs.dockerfile }}
          VAR3: ${{ inputs.registry }}
          VAR4: ${{ inputs.REGISTRY_USERNAME }}

        run: |
          missing=0

          for var in VAR1 VAR2 VAR3 VAR4; do
            if [ -z "${!var}" ]; then
              echo "ERROR: $var não definida"
              missing=1
            else
              echo "OK: $var definida"
            fi
          done

          exit $missing


      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Registry
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build
        run: |
          docker build \
            -f ${{ inputs.dockerfile }} \
            -t ${{ inputs.image_name }} .

      - name: Push
        run: |
          docker push \
            ${{ inputs.image_name }}